#!/usr/bin/env python3
"""
Assembles the static site into dist/ from site/{index.html,style.css,app.js,assets/}
plus data/{glossary.json,corpus.json}.

Copies index.html, style.css, app.js, and the assets/ directory as-is, and
generates dist/data.js which sets window.GLOSSARY and window.CORPUS -- the
only generated file. Keeping app.js static (not templated) means it's
cacheable across deploys and easy to lint/test on its own.

Note: data/glossary.json and data/corpus.json are expected to already exist
(generated by build_corpus.py from glossary.tsv and the .po files). This
script does not regenerate them.

Usage:
    python build_site.py --site-dir site --data-dir data --out-dir dist
"""
import argparse
import json
import os
import shutil
import sys


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--site-dir", required=True,
                         help="Directory containing index.html, style.css, app.js, assets/")
    parser.add_argument("--data-dir", required=True,
                         help="Directory containing glossary.json and corpus.json")
    parser.add_argument("--out-dir", required=True,
                         help="Output directory (e.g. dist/) to write the assembled site into")
    args = parser.parse_args()

    static_files = ["index.html", "style.css", "app.js"]
    for name in static_files:
        src = os.path.join(args.site_dir, name)
        if not os.path.isfile(src):
            print(f"ERROR: missing {src}", file=sys.stderr)
            sys.exit(1)

    glossary_path = os.path.join(args.data_dir, "glossary.json")
    corpus_path = os.path.join(args.data_dir, "corpus.json")

    with open(glossary_path, "r", encoding="utf-8") as f:
        glossary_json = f.read()
        json.loads(glossary_json)  # validate

    with open(corpus_path, "r", encoding="utf-8") as f:
        corpus_json = f.read()
        json.loads(corpus_json)  # validate

    os.makedirs(args.out_dir, exist_ok=True)

    for name in static_files:
        shutil.copyfile(os.path.join(args.site_dir, name), os.path.join(args.out_dir, name))
        print(f"Copied {name}", file=sys.stderr)

    # Copy any static assets (logo, images, etc.) referenced by relative
    # paths in index.html/style.css, e.g. assets/logo.svg -> dist/assets/logo.svg
    assets_src = os.path.join(args.site_dir, "assets")
    if os.path.isdir(assets_src):
        assets_dst = os.path.join(args.out_dir, "assets")
        if os.path.exists(assets_dst):
            shutil.rmtree(assets_dst)
        shutil.copytree(assets_src, assets_dst)
        copied = sum(len(files) for _, _, files in os.walk(assets_dst))
        print(f"Copied assets/ ({copied} file(s))", file=sys.stderr)
    else:
        print("No site/assets/ directory found, skipping", file=sys.stderr)

    data_js_path = os.path.join(args.out_dir, "data.js")
    with open(data_js_path, "w", encoding="utf-8") as f:
        f.write("window.GLOSSARY = ")
        f.write(glossary_json)
        f.write(";\nwindow.CORPUS = ")
        f.write(corpus_json)
        f.write(";\n")

    print(f"Wrote {data_js_path} ({os.path.getsize(data_js_path):,} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()